import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { CsrOpportunity } from '@prisma/client';
import { CsrOpportunityWithEvent } from '../csr-opportunities.repository';

type OpportunityEntity = CsrOpportunity | CsrOpportunityWithEvent;

function getEvent(opp: OpportunityEntity): { title: string; eventCode: string } | null {
  return 'event' in opp ? opp.event : null;
}

export class OpportunityResponseDto {
  @ApiProperty() id!: string;
  @ApiProperty() opportunityCode!: string;
  @ApiProperty() slug!: string;
  @ApiProperty() title!: string;
  @ApiPropertyOptional() eventId?: string | null;
  @ApiPropertyOptional() editionId?: string | null;
  @ApiProperty() opportunityType!: string;
  @ApiProperty() opportunityStatus!: string;
  @ApiProperty() shortDescription!: string;
  @ApiPropertyOptional() detailedDescription?: string | null;
  @ApiPropertyOptional() featuredImageKey?: string | null;
  @ApiPropertyOptional() bannerImageKey?: string | null;
  @ApiPropertyOptional() registrationOpens?: Date | null;
  @ApiPropertyOptional() registrationCloses?: Date | null;
  @ApiPropertyOptional() eventStartDate?: Date | null;
  @ApiPropertyOptional() eventEndDate?: Date | null;
  @ApiPropertyOptional() reportingTime?: string | null;
  @ApiPropertyOptional() closingTime?: string | null;
  @ApiProperty() timeZone!: string;
  @ApiProperty() mode!: string;
  @ApiPropertyOptional() venue?: string | null;
  @ApiPropertyOptional() address?: string | null;
  @ApiPropertyOptional() landmark?: string | null;
  @ApiPropertyOptional() district?: string | null;
  @ApiPropertyOptional() state?: string | null;
  @ApiPropertyOptional() pincode?: string | null;
  @ApiPropertyOptional() googleMapsUrl?: string | null;
  @ApiPropertyOptional() meetingLink?: string | null;
  @ApiPropertyOptional() platform?: string | null;
  @ApiProperty() volunteersRequired!: number;
  @ApiProperty() maxApplications!: number;
  @ApiPropertyOptional() minAge?: number | null;
  @ApiPropertyOptional() maxAge?: number | null;
  @ApiProperty() genderRestriction!: string;
  @ApiProperty() experienceRequired!: boolean;
  @ApiProperty({ type: [String] }) requiredSkills!: string[];
  @ApiPropertyOptional() physicalRequirements?: string | null;
  @ApiPropertyOptional() coordinatorName?: string | null;
  @ApiPropertyOptional() coordinatorDesignation?: string | null;
  @ApiPropertyOptional() coordinatorEmail?: string | null;
  @ApiPropertyOptional() coordinatorMobile?: string | null;
  @ApiPropertyOptional() coordinatorAltMobile?: string | null;
  @ApiPropertyOptional() formConfig?: unknown;
  @ApiProperty({ type: [String] }) requiredDocuments!: string[];
  @ApiProperty({ type: [String] }) galleryImageKeys!: string[];
  @ApiPropertyOptional() brochureKey?: string | null;
  @ApiProperty({ type: [String] }) supportingDocKeys!: string[];
  @ApiProperty() showOnHomepage!: boolean;
  @ApiProperty() showOnCsrPage!: boolean;
  @ApiProperty() isFeatured!: boolean;
  @ApiProperty() acceptRegistrations!: boolean;
  @ApiProperty() showCountdown!: boolean;
  @ApiPropertyOptional() metaTitle?: string | null;
  @ApiPropertyOptional() metaDescription?: string | null;
  @ApiPropertyOptional() ogImageKey?: string | null;
  @ApiProperty() workflowType!: string;
  @ApiProperty() notifyRegistration!: boolean;
  @ApiProperty() notifyApproval!: boolean;
  @ApiProperty() notifyRejection!: boolean;
  @ApiProperty() notifyReminder!: boolean;
  @ApiPropertyOptional() adminNotes?: string | null;
  @ApiProperty() version!: number;
  @ApiProperty() createdAt!: Date;
  @ApiProperty() updatedAt!: Date;
  @ApiPropertyOptional() eventTitle?: string | null;
  @ApiPropertyOptional() eventCode?: string | null;

  static fromEntity(opp: OpportunityEntity): OpportunityResponseDto {
    const dto = new OpportunityResponseDto();
    dto.id = opp.id;
    dto.opportunityCode = opp.opportunityCode;
    dto.slug = opp.slug;
    dto.title = opp.title;
    dto.eventId = opp.eventId;
    dto.editionId = opp.editionId;
    dto.opportunityType = opp.opportunityType;
    dto.opportunityStatus = opp.opportunityStatus;
    dto.shortDescription = opp.shortDescription;
    dto.detailedDescription = opp.detailedDescription;
    dto.featuredImageKey = opp.featuredImageKey;
    dto.bannerImageKey = opp.bannerImageKey;
    dto.registrationOpens = opp.registrationOpens;
    dto.registrationCloses = opp.registrationCloses;
    dto.eventStartDate = opp.eventStartDate;
    dto.eventEndDate = opp.eventEndDate;
    dto.reportingTime = opp.reportingTime;
    dto.closingTime = opp.closingTime;
    dto.timeZone = opp.timeZone;
    dto.mode = opp.mode;
    dto.venue = opp.venue;
    dto.address = opp.address;
    dto.landmark = opp.landmark;
    dto.district = opp.district;
    dto.state = opp.state;
    dto.pincode = opp.pincode;
    dto.googleMapsUrl = opp.googleMapsUrl;
    dto.meetingLink = opp.meetingLink;
    dto.platform = opp.platform;
    dto.volunteersRequired = opp.volunteersRequired;
    dto.maxApplications = opp.maxApplications;
    dto.minAge = opp.minAge;
    dto.maxAge = opp.maxAge;
    dto.genderRestriction = opp.genderRestriction;
    dto.experienceRequired = opp.experienceRequired;
    dto.requiredSkills = opp.requiredSkills;
    dto.physicalRequirements = opp.physicalRequirements;
    dto.coordinatorName = opp.coordinatorName;
    dto.coordinatorDesignation = opp.coordinatorDesignation;
    dto.coordinatorEmail = opp.coordinatorEmail;
    dto.coordinatorMobile = opp.coordinatorMobile;
    dto.coordinatorAltMobile = opp.coordinatorAltMobile;
    dto.formConfig = opp.formConfig;
    dto.requiredDocuments = opp.requiredDocuments;
    dto.galleryImageKeys = opp.galleryImageKeys;
    dto.brochureKey = opp.brochureKey;
    dto.supportingDocKeys = opp.supportingDocKeys;
    dto.showOnHomepage = opp.showOnHomepage;
    dto.showOnCsrPage = opp.showOnCsrPage;
    dto.isFeatured = opp.isFeatured;
    dto.acceptRegistrations = opp.acceptRegistrations;
    dto.showCountdown = opp.showCountdown;
    dto.metaTitle = opp.metaTitle;
    dto.metaDescription = opp.metaDescription;
    dto.ogImageKey = opp.ogImageKey;
    dto.workflowType = opp.workflowType;
    dto.notifyRegistration = opp.notifyRegistration;
    dto.notifyApproval = opp.notifyApproval;
    dto.notifyRejection = opp.notifyRejection;
    dto.notifyReminder = opp.notifyReminder;
    dto.adminNotes = opp.adminNotes;
    dto.version = opp.version;
    dto.createdAt = opp.createdAt;
    dto.updatedAt = opp.updatedAt;
    const event = getEvent(opp);
    dto.eventTitle = event?.title ?? null;
    dto.eventCode = event?.eventCode ?? null;
    return dto;
  }
}

export class OpportunityListItemDto {
  @ApiProperty() id!: string;
  @ApiProperty() opportunityCode!: string;
  @ApiProperty() slug!: string;
  @ApiProperty() title!: string;
  @ApiProperty() opportunityType!: string;
  @ApiProperty() opportunityStatus!: string;
  @ApiProperty() shortDescription!: string;
  @ApiPropertyOptional() district?: string | null;
  @ApiPropertyOptional() state?: string | null;
  @ApiProperty() mode!: string;
  @ApiPropertyOptional() registrationCloses?: Date | null;
  @ApiProperty() volunteersRequired!: number;
  @ApiProperty() maxApplications!: number;
  @ApiProperty() isFeatured!: boolean;
  @ApiProperty() acceptRegistrations!: boolean;
  @ApiProperty() createdAt!: Date;
  @ApiPropertyOptional() eventTitle?: string | null;

  static fromEntity(opp: OpportunityEntity): OpportunityListItemDto {
    const dto = new OpportunityListItemDto();
    dto.id = opp.id;
    dto.opportunityCode = opp.opportunityCode;
    dto.slug = opp.slug;
    dto.title = opp.title;
    dto.opportunityType = opp.opportunityType;
    dto.opportunityStatus = opp.opportunityStatus;
    dto.shortDescription = opp.shortDescription;
    dto.district = opp.district;
    dto.state = opp.state;
    dto.mode = opp.mode;
    dto.registrationCloses = opp.registrationCloses;
    dto.volunteersRequired = opp.volunteersRequired;
    dto.maxApplications = opp.maxApplications;
    dto.isFeatured = opp.isFeatured;
    dto.acceptRegistrations = opp.acceptRegistrations;
    dto.createdAt = opp.createdAt;
    dto.eventTitle = getEvent(opp)?.title ?? null;
    return dto;
  }
}
